spring.application.name=mission-archive-hub
server.port=1488

archive.jdbc.url=jdbc:postgresql://localhost:5432/mission_archive
archive.jdbc.username=postgres
archive.jdbc.password=postgres

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.api-docs.path=/v3/api-docs
